<?php

/**
 * Banner_Model_StatuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Banner_Model_StatuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Banner_Model_StatuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Banner_Model_Statu');
    }
}