<?$this->headScript()->captureStart() ?>
	var materials = <?php echo json_encode($this->materialsJSON); ?>;
	var tags = <?php echo json_encode($this->tagsJSON); ?>;
	var photos = <?=json_encode(($this->photos))?>;
<? $this->headScript()->captureEnd(); ?>
<? $this->headLink()->appendStylesheet('/css/jquery/jquery.fileupload-ui.css'); ?>
<? $this->headScript()->appendFile('/js/product/index/edit.js'); ?>
<? $this->headScript()->appendFile('/js/jquery/jquery.tmpl.min.js'); ?>
<? $this->headScript()->appendFile('/js/jquery/jquery.iframe-transport.js'); ?>
<? $this->headScript()->appendFile('/js/jquery/jquery.fileupload.js'); ?>
<? $this->headScript()->appendFile('/js/jquery/jquery.fileupload-ui.js'); ?>
<? $this->headScript()->appendFile('/js/upload.js'); ?>
<div class="styledform" style="margin-top:20px">
	<h3>Редактирование товара</h3>
	<form action="<?=$this->escape($this->form->getAction());?>" method="<?=$this->escape($this->form->getMethod());?>" id="<?=$this->form->getAttrib('id');?>">
		<table class="create_shop">
			<tr>
                            <td class="label"><?=$this->form->title->getLabel();?>&nbsp;<span class="required_field_mark">*</span></td>
                            <td class="data"><?=$this->form->title; ?></td>
			</tr>
			<tr>
                            <td class="label"><?=$this->form->categories->getLabel();?>&nbsp;<span class="required_field_mark">*</span></td>
                            <td class="data"><?=$this->form->categories; ?></td>
			</tr>
			<tr>
                            <td class="label"><?=$this->form->subCategories->getLabel();?>&nbsp;<span class="required_field_mark">*</span></td>
                            <td class="data"><?=$this->form->subCategories; ?></td>
			</tr>
			<tr>
                            <td class="label"><?=$this->form->price->getLabel();?>&nbsp;<span class="required_field_mark">*</span></td>
                            <td class="data"><?=$this->form->price; ?>&nbsp;руб.</td>
			</tr>
			<tr>
                            <td class="label"><?=$this->form->description->getLabel();?>&nbsp;<span class="required_field_mark">*</span></td>
                            <td class="data"><?=$this->form->description; ?></td>
			</tr>
			<tr>
                            <td class="label"><?=$this->form->production_time->getLabel();?></td>
                            <td class="data"><?=$this->form->production_time; ?></td>
			</tr>
			<tr>
                            <td class="label"><?=$this->form->size->getLabel();?></td>
                            <td class="data"><?=$this->form->size; ?></td>
			</tr>
			<tr>
                            <td class="label"><?=$this->form->availlable_id->getLabel();?></td>
                            <td class="data">
                                    <?=$this->form->availlable_id; ?>
                                    <?=$this->form->quantity; ?>
                            </td>
			</tr>
			<tr>
                            <td class="label">Материал</td>
                            <td class="data">
                                <style>
                                        #select_tag{width:311px;}
                                        #select_material{width:311px;}
                                        #product_form_index_add_color-1,#product_form_index_add_color-2,#product_form_index_add_color-3 {width:130px;}
                                </style>
                                <?=$this->autoComplete("select_material", "", array("url"=>"/product/index/ajaxeditproductautocomplete/?type=material")); ?>
                                <button id="add_material" name="add_mark">Добавить</button>
                                <div id="selected_materials">
                                    <?php if (count($this->materials)): ?>
                                        <?
                                           $end_material_id = end($this->materials);
                                           $end_materail_id = $end_material_id['material_id'];
                                        ?>
                                        <?php foreach($this->materials as &$material): ?>
                                        <span>
                                            <span><?php echo $material['title']; ?></span>
                                            <a href="javascript:void(0)" name="delete_mark">Удалить</a>
                                            <?php (($material['material_id']!=$end_material_id) ? ',&nbsp;' : ''); ?>
                                        </span>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </div>
                                <?=$this->form->materials;?>
                            </td>
			</tr>
			<tr>
                            <td class="label">Тэги</td>
                            <td class="data">
                                    <?=$this->autoComplete("select_tag", "", array("url"=>"/product/index/ajaxeditproductautocomplete/?type=tag")); ?>
                                    <button id="add_tag" name="add_mark">Добавить</button>
                                    <div id="selected_tags">
                                        <?php if (count($this->tags)): ?>
                                            <?
                                               $end_tag_id = end($this->tags);
                                               $end_tag_id = $end_tag_id['tag_id'];
                                            ?>
                                            <?php foreach($this->tags as &$tag): ?>
                                            <span>
                                                <span><?php echo $tag['title']; ?></span>
                                                <a href="javascript:void(0)" name="delete_mark">Удалить</a>
                                                <?php (($tag['tag_id']!=$end_tag_id) ? ',&nbsp;' : ''); ?>
                                            </span>
                                            <?php endforeach; ?>
                                        <?php endif; ?>
                                    </div>
                                    <?	if(count($this->tags)) {
                                            echo '<a href="javascript:void(0)" name="showTags">Показать все мои теги</a>';
                                            $str = '';
                                            $end_tag_id = end($this->tags);
                                            $end_tag_id = $end_tag_id['tag_id'];
                                            $token = ',&nbsp;';
                                            foreach($this->tags as &$tag) {
                                                    $str .= '<a href="javascript:void(0)" name="add_tag">'.$tag['title'].'</a>'.(($tag['tag_id']!=$end_tag_id) ? $token : '');
                                            }
                                            echo '<div style="display: none;">'.$str.'</div>';
                                    } ?>
                                    <?=$this->form->tags;?>					
                            </td>
			</tr>
			<tr>
				<td class="label">Цвет</td>
				<td class="data">
                                    <select id="product_form_index_add_color-1" name="color[]">
                                        <? if(count($this->user_colors) >= 1): ?>
                                           <option value="0" <? ($this->user_colors[0]->color_id == 0) ? 'SELECTED="SELECTED" ' : ''; ?>>Выберите цвет</option>
                                            <? foreach($this->colors as $key => $color): ?>
                                                <option <? echo ($this->user_colors[0]->color_id ==  $key) ? 'selected="selected"' : ''; ?> value="<?php echo $key; ?>"><?php echo $color; ?></option>
                                            <? endforeach; ?>
                                        <? else: ?>
                                            <option value="0" SELECTED>Выберите цвет</option>
                                            <? foreach($this->colors as $key => $color): ?>
                                                <option value="<?php echo $key; ?>"><?php echo $color; ?></option>
                                            <? endforeach; ?>
                                        <? endif; ?>
                                    </select>
                                    <select id="product_form_index_add_color-2" name="color[]">
                                        <? if(count($this->user_colors) >= 2): ?>
                                           <option value="0" <? ($this->user_colors[1]->color_id == 0) ? 'SELECTED="SELECTED" ' : ''; ?>>Выберите цвет</option>
                                            <? foreach($this->colors as $key => $color): ?>
                                                <option <? echo ($this->user_colors[1]->color_id ==  $key) ? 'selected="selected"' : ''; ?> value="<?php echo $key; ?>"><?php echo $color; ?></option>
                                            <? endforeach; ?>
                                        <? else: ?>
                                            <option value="0" SELECTED>Выберите цвет</option>
                                            <? foreach($this->colors as $key => $color): ?>
                                                <option value="<?php echo $key; ?>"><?php echo $color; ?></option>
                                            <? endforeach; ?>
                                        <? endif; ?>
                                    </select>
                                    <select id="product_form_index_add_color-3" name="color[]">
                                        <? if(count($this->user_colors) == 3): ?>
                                           <option value="0" <? ($this->user_colors[2]->color_id == 0) ? 'SELECTED="SELECTED" ' : ''; ?>>Выберите цвет</option>
                                            <? foreach($this->colors as $key => $color): ?>
                                                <option <? echo ($this->user_colors[2]->color_id ==  $key) ? 'selected="selected"' : ''; ?> value="<?php echo $key; ?>"><?php echo $color; ?></option>
                                            <? endforeach; ?>
                                        <? else: ?>
                                            <option value="0" SELECTED>Выберите цвет</option>
                                            <? foreach($this->colors as $key => $color): ?>
                                                <option value="<?php echo $key; ?>"><?php echo $color; ?></option>
                                            <? endforeach; ?>
                                        <? endif; ?>
                                    </select>
				</td>
			</tr>
		</table>
		<?=$this->form->photos;?>
	</form>
	<table class="create_shop">
		<tr>
			<td class="label" style="width:155px;">Загрузить фотографии</td>
			<td class="data" style="width:500px;">
				<div id="fileupload">
					<form action="/index/index/upload/" method="POST" enctype="multipart/form-data" style="margin: 0;">
						<div class="fileupload-buttonbar">
							<label class="fileinput-button">
								<span>Добавить...</span>
								<input type="file" name="files[]" multiple>
							</label>
						</div>
					</form>
					<div class="fileupload-content">
						<table class="files"></table>
						<div class="fileupload-progressbar" style="display: none;"></div>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td></td>
			<td><?=$this->form->submit_validator; ?></td>
		</tr>
	</table>
</div>
<script id="template-upload" type="text/x-jquery-tmpl">
    <tr class="template-upload{{if error}} ui-state-error{{/if}}">
        <td class="preview"></td>
        {{if error}}
            <td class="error" colspan="2">Error:
                {{if error === 'maxFileSize'}}File is too big
                {{else error === 'minFileSize'}}File is too small
                {{else error === 'acceptFileTypes'}}Filetype not allowed
                {{else error === 'maxNumberOfFiles'}}Max number of files exceeded
                {{else}}${error}
                {{/if}}
            </td>
        {{else}}
            <td class="progress"><div></div></td>
            <td class="start"><button>Start</button></td>
        {{/if}}
        <td class="cancel"><button>Cancel</button></td>
    </tr>
</script>
<script id="template-download" type="text/x-jquery-tmpl">
    <tr class="template-download{{if error}} ui-state-error{{/if}}">
        {{if error}}
            <td></td>
            <td class="error" colspan="2">Error:
                {{if error === 1}}File exceeds upload_max_filesize (php.ini directive)
                {{else error === 2}}File exceeds MAX_FILE_SIZE (HTML form directive)
                {{else error === 3}}File was only partially uploaded
                {{else error === 4}}No File was uploaded
                {{else error === 5}}Missing a temporary folder
                {{else error === 6}}Failed to write file to disk
                {{else error === 7}}File upload stopped by extension
                {{else error === 'maxFileSize'}}File is too big
                {{else error === 'minFileSize'}}File is too small
                {{else error === 'acceptFileTypes'}}Filetype not allowed
                {{else error === 'maxNumberOfFiles'}}Max number of files exceeded
                {{else error === 'uploadedBytes'}}Uploaded bytes exceed file size
                {{else error === 'emptyResult'}}Empty file upload result
                {{else}}${error}
                {{/if}}
            </td>
        {{else}}
            <td class="preview">
                {{if thumbnail_url}}
                    <a href="${url}" target="_blank"><img src="${thumbnail_url}"></a>
                {{/if}}
            </td>
        {{/if}}
        <td class="delete">
            <button data-type="${delete_type}" data-url="${delete_url}">Delete</button>
        </td>
        <td class="setAvatar">
<label for="${name}"><input type="radio" name="isMainPhoto" value="1" ${checked} id="${name}">Сделать основной</label>
        </td>
        <td>
{{if desc}}
<input type="text" name="desc[]" value="${desc}">
{{else}}
<input type="text" name="desc[]" value="">
{{/if}}
        </td>
    </tr>
</script>