<?php $this->headLink()->appendStylesheet('/stylesheets/jquery/jquery.fileupload-ui.css'); ?>
<?php $this->headScript()->appendFile('/javascripts/jquery/jquery.tmpl.min.js'); ?>
<?php $this->headScript()->appendFile('/javascripts/jquery/jquery.iframe-transport.js'); ?>
<?php $this->headScript()->appendFile('/javascripts/jquery/jquery.fileupload.js'); ?>
<?php $this->headScript()->appendFile('/javascripts/jquery/jquery.fileupload-ui.js'); ?>
<?php $this->headScript()->appendFile('/javascripts/upload.js'); ?>
<script id="template-upload" type="text/x-jquery-tmpl">
    <tr class="template-upload{{if error}} ui-state-error{{/if}}">
        <td class="preview"></td>
        {{if error}}
            <td class="error" colspan="2">Error:
                {{if error === 'maxFileSize'}}File is too big
                {{else error === 'minFileSize'}}File is too small
                {{else error === 'acceptFileTypes'}}Filetype not allowed
                {{else error === 'maxNumberOfFiles'}}Max number of files exceeded
                {{else}}${error}
                {{/if}}
            </td>
        {{else}}
            <td class="progress"><div></div></td>
            <td class="start"><button>Start</button></td>
        {{/if}}
        <td class="cancel"><button>Cancel</button></td>
    </tr>
</script>
<script id="template-download" type="text/x-jquery-tmpl">
    <tr class="template-download{{if error}} ui-state-error{{/if}}">
        {{if error}}
            <td></td>
            <td class="error" colspan="2">Error:
                {{if error === 1}}File exceeds upload_max_filesize (php.ini directive)
                {{else error === 2}}File exceeds MAX_FILE_SIZE (HTML form directive)
                {{else error === 3}}File was only partially uploaded
                {{else error === 4}}No File was uploaded
                {{else error === 5}}Missing a temporary folder
                {{else error === 6}}Failed to write file to disk
                {{else error === 7}}File upload stopped by extension
                {{else error === 'maxFileSize'}}File is too big
                {{else error === 'minFileSize'}}File is too small
                {{else error === 'acceptFileTypes'}}Filetype not allowed
                {{else error === 'maxNumberOfFiles'}}Max number of files exceeded
                {{else error === 'uploadedBytes'}}Uploaded bytes exceed file size
                {{else error === 'emptyResult'}}Empty file upload result
                {{else}}${error}
                {{/if}}
            </td>
        {{else}}
            <td class="preview">
                {{if thumbnail_url}}
                    <a href="${url}" target="_blank"><img src="${thumbnail_url}"></a>
                {{/if}}
            </td>
        {{/if}}
        <td class="delete">
            <button data-type="${delete_type}" data-url="${delete_url}">Delete</button>
        </td>
        <td class="setAvatar">
            <a href="javascript:void(0)" name="isMainPhoto" id="${name}">Сделать основной</a>
        </td>
        <td>
            <input type="text" name="desc" value="">
        </td>
    </tr>
</script>
<?$this->headScript()->captureStart() ?>
	var materials = <?php echo json_encode($this->materialsJSON); ?>;
	var tags = <?php echo json_encode($this->tagsJSON); ?>;
	var photos = new Array();
<? $this->headScript()->captureEnd(); ?>
<script>
jQuery(document).ready(function() {
	jQuery('#categories').prepend('<option value="0" selected="selected">Выберите категорию</option>')
	
	//выбор цвета
	jQuery('[name="color[]"]').change(function(){
		if(this.value == 0) return false;
		var last_val = jQuery(this).data('last_val');
		var value = jQuery(this).val();    
		var id = jQuery(this).attr('id');  
		jQuery(this).data('last_val',value);
		
		jQuery.each(jQuery('[name="color[]"]'),function(i,child){
			if(jQuery(child).attr('id')!=id) {
				jQuery("#"+jQuery(child).attr('id')+" > option[value='"+value+"']").hide();
				jQuery("#"+jQuery(child).attr('id')+" > option[value='"+last_val+"']").show();
			}
		});
	});
	
	//выбор категории
	jQuery('#categories').change( function(){
        var subCategories = $('select[name="subCategories"]');
		if(jQuery('#categories').val()==0){
			subCategories.html('<option value="0" selected="selected">Выберите категорию</option>');
			return false;
		}
        jQuery.getJSON('/product/index/getcategories/?parent_id='+jQuery('#categories').val(), function(data) {
                subCategories.html('');
                jQuery.each(data.categories, function(i){
                    subCategories.append('<option value="' + i + '">' + this + '</option>');
                });
            });
        });
        
        //выбор главной картинки
	jQuery('[name="isMainPhoto"]').live('click',function(event) {
		photos['main'] = 'sdsdsd';	
		console.log(photos);
	});
        
	//валидация формы
	jQuery('[name="submit_validator"]').bind('click',function(event) {
		event.preventDefault();
		var form =  jQuery('#mainform');
		var form_id = jQuery(form).attr('id');
		var action = jQuery(form).attr('action');
		jQuery(this).after('<div class="preloader"><span>Идет проверка</span></div>');
		
		jQuery.post(action, jQuery(form).serialize(),function(data){
			if(data.error==0) {
				jQuery('#materials').val(serialize(materials));
				jQuery('#tags').val(serialize(tags));
				jQuery(form).submit();
			}
			jQuery('#'+form_id+ ' .not_valid').removeClass('not_valid');
			jQuery('#'+form_id+ ' .errors').remove();
			jQuery.each(data.error,function(key,err){
				jQuery('#'+key).addClass('not_valid');
			})
			jQuery('#'+form_id+ ' .preloader').remove();
		});		
	});
        
	//наличие товара
	jQuery('#availlable_id').change( function(){
        var availlable_val = jQuery('#availlable_id').val();
        if(availlable_val == 1) jQuery("#quantity").attr("style", "display:inline");
        else jQuery("#quantity").attr("style", "display:none");
        });
	//показ своих тэгов
	jQuery('[name="showTags"]').click(function() {
		jQuery(this).next().stop(true, true).toggle('500');
		if(jQuery(this).data('status')=='up') {
			jQuery(this).text('Показать все мои теги');
			jQuery(this).data('status','down');
		} else {
			jQuery(this).text('Скрыть');
			jQuery(this).data('status','up');
		}
	});
        
	//добавление материалов и тэгов
	jQuery('[name="add_mark"]').click(function(event) {
		event.preventDefault();
		addMark(this.id,jQuery(this).next().attr('id'),jQuery(this).prev().val());
	}); 
        
	//удаление материалов и тэгов
	jQuery('[name="delete_mark"]').live('click',function() {
		var value = jQuery(this).prev().text();
		if(jQuery(this).parent().parent().attr('id')=='selected_materials') var data = materials;
		else var data = tags;	
		
		for (var i=0; i<=data.length-1; i++){
			if(data[i]==value) break;
		}
		data.splice(i,1);
		jQuery(this).parent().remove();
	});
        
        //добавление тега
	jQuery('[name="add_tag"]').click(function(event){
		event.preventDefault();
		addMark('add_tag','selected_tags',jQuery(this).text(),true);
	});
        
	//фукнция добавления
	function addMark(id,id_marks,value,simple_tag) {
		var value = jQuery.trim(value);
		if(value=='') {			
			if(!jQuery('#'+id).prev().hasClass('not_valid')) {
				jQuery('#'+id).prev().addClass('not_valid')
			}			
			return false;
		}
		var error = 0;			
		if(id=='add_material') var data = materials;
		else var data = tags;			
		jQuery.each(data,function(i,result){
			if(value==result) error++;
		});
		if(error>0) {
			if(simple_tag!=true) {
				if(!jQuery('#'+id).prev().hasClass('not_valid')) {
					jQuery('#'+id).prev().addClass('not_valid')
				}
			}
			return false;
		}
		jQuery('#'+id).prev().removeClass('not_valid');
		data.push(value);
		if(jQuery('#'+id_marks).children('span').length!=0) {
			jQuery(jQuery('#'+id_marks).children('span')[((jQuery('#'+id_marks).children('span').length)-1)]).append(', ')
		}
		jQuery('#'+id_marks).append('<span><span>'+value+'</span><a href="javascript:void(0)" name="delete_mark">Удалить</a></span>');
		jQuery('#'+id).prev().val('');
	}
});
</script>
<div class="styledform" style="margin-top:20px; width: 50%;">
    <h3>Добавление товара</h3>
    <form  id="mainform" action="<?php echo $this->escape($this->form->getAction());?>" method="<?php echo $this->escape($this->form->getMethod());?>">
        <table style="width: 50%;">
            <tr>
                <td class="label"><?php echo $this->form->title->getLabel(); ?></td>
                <td class="data"><?php echo $this->form->title; ?></td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->form->categories->getLabel(); ?></td>
                <td class="data"><?php echo $this->form->categories; ?></td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->form->subCategories->getLabel(); ?></td>
                <td class="data"><?php echo $this->form->subCategories; ?></td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->form->price->getLabel(); ?></td>
                <td class="data"><?php echo $this->form->price; ?></td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->form->description->getLabel(); ?></td>
                <td class="data"><?php echo $this->form->description; ?></td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->form->production_time->getLabel(); ?></td>
                <td class="data"><?php echo $this->form->production_time; ?></td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->form->size->getLabel(); ?></td>
                <td class="data"><?php echo $this->form->size; ?></td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->form->availlable_id->getLabel(); ?></td>
                <td class="data">
                    <?php echo $this->form->availlable_id; ?>
                    <?php if ($this->form->availlable_id->getValue() != 1) $this->form->getElement('quantity')->setAttrib('style', 'display:none;'); ?>
                    <?php echo $this->form->quantity; ?>
                </td>
            </tr>
            <tr>
                <td class="label">материал</td>
                <td class="data">
                    <?php echo $this->autoComplete("select_material", "", array("url"=>"/product/index/ajaxeditproductautocomplete/?type=material")); ?>
                    <button id="add_material" name="add_mark">Добавить</button>
                    <div id="selected_materials">
                    <?php if (count($this->materials)): ?>
                        <?
                           $end_material_id = end($this->materials);
                           $end_materail_id = $end_material_id['material_id'];
                        ?>
                        <?php foreach($this->materials as &$material): ?>
                        <span>
                            <span><?php echo $material['title']; ?></span>
                            <a href="javascript:void(0)" name="delete_mark">Удалить</a>
                            <?php (($material['material_id']!=$end_material_id) ? ',&nbsp;' : ''); ?>
                        </span>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    </div>
                    <?php echo $this->form->materials;?>
                </td>
            </tr>
            <tr>
                <td class="label">
                    Теги
                </td>
                <td class="data">
                    <?php echo  $this->autoComplete("select_tag", "", array("url"=>"/product/index/ajaxeditproductautocomplete/?type=tag")); ?>
                    <button id="add_tag" name="add_mark">Добавить</button>
                    <div id="selected_tags">
                    <?php if (count($this->tags)): ?>
                        <?
                           $end_tag_id = end($this->tags);
                           $end_tag_id = $end_tag_id['tag_id'];
                        ?>
                        <?php foreach($this->tags as &$tag): ?>
                        <span>
                            <span><?php echo $tag['title']; ?></span>
                            <a href="javascript:void(0)" name="delete_mark">Удалить</a>
                            <?php (($tag['tag_id']!=$end_tag_id) ? ',&nbsp;' : ''); ?>
                        </span>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    </div>
                    <?php if (count($this->user_tags)): ?>
                        <a href="javascript:void(0)" name="showTags">Показать все мои теги</a>
                        <?
                           $end_tag_id = end($this->user_tags);
                           $end_tag_id = $end_tag_id['tag_id'];
                        ?>
                        <div style="display: none;">
                        <?php foreach($this->user_tags as &$tag): ?>
                            <a href="javascript:void(0)" name="add_tag"><?php echo $tag['title']; ?></a><?php (($tag['tag_id']!=$end_tag_id) ? ',&nbsp;' : ''); ?>
                        <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                    <?php echo $this->form->user_tags; ?>
                </td>
            </tr>
            <tr>
                <td class="label">Цвета</td>
                <td class="data">
                <select id="color1" name="color[]">
                   <option value="0" SELECTED>Выберите цвет</option>
                    <? foreach($this->colors as $key => $color): ?>
                        <option value="<?php echo $key; ?>"><?php echo $color; ?></option>
                    <? endforeach; ?>
                </select>
                <select id="color2" name="color[]">
                    <option value="0" SELECTED>Выберите цвет</option>
                    <? foreach($this->colors as $key => $color): ?>
                        <option value="<?php echo $key; ?>"><?php echo $color; ?></option>
                    <? endforeach; ?>
                </select>
                <select id="color3" name="color[]">
                   <option value="0" SELECTED>Выберите цвет</option>
                    <? foreach($this->colors as $key => $color): ?>
                        <option value="<?php echo $key; ?>"><?php echo $color; ?></option>
                    <? endforeach; ?>
                </select>
                </td>
            </tr>
            </form>
            <tr>
                <td>Загрузить фотографии товара</td>
                <td>
                    <div id="fileupload">
                        <form action="/upload.php" method="POST" enctype="multipart/form-data" style="margin: 0;">
                            <div class="fileupload-buttonbar">
                                <label class="fileinput-button">
                                    <span>Add files...</span>
                                    <input type="file" name="files[]" multiple>
                                </label>
                            </div>
                        </form>
                        <div class="fileupload-content">
                            <table class="files"></table>
                            <div class="fileupload-progressbar" style="display: none;"></div>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td></td>
                <td><?php echo $this->form->submit_validator; ?></td>
            </tr>
        </table>
</div>