---
detect_relations: true
options:
  collate: utf8_general_ci
  charset: utf8
  type: InnoDB

Index_Model_Profile:
  columns:
    id:
      type: integer(11)
      primary: true
      notnull: true
    name:
      type: string(255)
      notnull: true
    money:
      type: float
      notnull: true
      default: 0
    active:
      type: boolean
      notnull: true
      default: 1
  options:
    charset: utf8
    collate: utf8_general_ci

Index_Model_Deal:
  columns:
    id:
      type: integer(11)
      primary: true
      notnull: true
      autoincrement: true
    category_id:
      type: integer(11)
      notnull: true
    firm_id:
      type: integer(11)
      notnull: true
    name:
      type: string(255)
      notnull: true
    title:
      type: text
      notnull: true
    description:
      type: text
      notnull: true
    price:
      type: integer(11)
      notnull: true
    discount:
      type: integer(11)
      notnull: true
    min_buy:
      type: integer(11)
      notnull: true
      default: 0
    max_buy:
      type: integer(11)
      notnull: true
      default: 0
    total_price:
      type: integer(11)
      notnull: true
    extra:
      type: text
    conditions:
      type: text
      notnull: true
    rating:
      type: integer(11)
      notnull: true
      default: 100
    date_start:
      type: datetime
      notnull: true
    date_end:
      type: datetime
      notnull: true
    coupon_paid:
      type: integer(11)
    coupon_ordered:
      type: integer(11)
    image_url:
      type: string(255)
      notnull: true
    image_alt:
      type: string(255)
      notnull: false
    use_start:
      type: datetime
      notnull: false
    use_end:
      type: datetime
      notnull: false
  relations:
    category:
      class: Index_Model_Category
      local: category_id
      foreign: id
      foreignAlias: deals
      foreignType: many
      owningSide: true
  indexes:
    fk_deal_1:
      fields: [category_id]
  options:
    charset: utf8
    collate: utf8_general_ci

Index_Model_Comment:
  columns:
    id:
      type: integer(11)
      primary: true
      notnull: true
      autoincrement: true
    deal_id:
      type: integer(11)
      notnull: true
    user_id:
      type: integer(11)
      notnull: true
    text:
      type: text
      notnull: true
    date:
      type: datetime
      notnull: true
  relations:
    profile:
      class: Index_Model_Profile
      local: user_id
      foreign: id
      foreignAlias: comments
      foreignType: many
      owningSide: true
    deal:
      class: Index_Model_Deal
      local: deal_id
      foreign: id
      foreignAlias: comments
      foreignType: many
      owningSide: true
  indexes:
    fk_comment_1:
      fields: [user_id]
    fk_comment_2:
      fields: [deal_id]
  options:
    charset: utf8
    collate: utf8_general_ci

Index_Model_Category:
  columns:
    id:
      type: integer(11)
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(255)
    title:
      type: string(255)
      notnull: true
    description:
      type: text
      notnull: true

Index_Model_Image:
  columns:
    id:
      type: integer(11)
      primary: true
      notnull: true
      autoincrement: true
    deal_id:
      type: integer(11)
      notnull: true
    url:
      type: string(255)
      notnull: true
    alt:
      type: string(255)
    main:
      type: boolean
      notnull: true
      default: 0
  relations:
    deal:
      class: Index_Model_Deal
      local: deal_id
      foreign: id
      foreignAlias: images
      foreignType: many
      owningSide: true
  indexes:
    fk_image_1:
      fields: [deal_id]
  options:
    charset: utf8
    collate: utf8_general_ci

Index_Model_Coupon:
  columns:
    id:
      type: integer(11)
      primary: true
      notnull: true
      autoincrement: true
    deal_id:
      type: integer(11)
      notnull: true
    user_id:
      type: integer(11)
      notnull: true
    code:
      type: string(10)
      notnull: true
    paid:
      type: boolean
      notnull: true
      default: 0
    date_paid:
      type: datetime
  relations:
    deal:
      class: Index_Model_Deal
      local: deal_id
      foreign: id
      foreignAlias: coupons
      foreignType: many
      owningSide: true
    profile:
      class: Index_Model_Profile
      local: user_id
      foreign: id
      foreignAlias: coupons
      foreignType: many
      owningSide: true
  indexes:
    fk_coupon_1:
      fields: [deal_id]
    fk_coupon_2:
      fields: [user_id]

Index_Model_Transaction:
  columns:
    id:
      type: integer(11)
      primary: true
      notnull: true
      autoincrement: true
    user_id:
      type: integer(11)
      notnull: true
    transaction:
      type: text
      notnull: true
    date:
      type: datetime
      notnull: true
  relations:
    profile:
      class: Index_Model_Profile
      local: user_id
      foreign: id
      foreignAlias: transactions
      foreignType: many
      owningSide: true
  indexes:
    fk_log_1:
      fields: [user_id]
  options:
    charset: utf8
    collate: utf8_general_ci

Index_Model_Log:
  columns:
    id:
      type: integer(11)
      primary: true
      notnull: true
      autoincrement: true
    text:
      type: text
      notnull: true
    date:
      type: datetime
      notnull: true
  options:
    charset: utf8
    collate: utf8_general_ci

Index_Model_Check:
  columns:
    id:
      type: integer(11)
      primary: true
      notnull: true
      autoincrement: true
    id_user:
      type: integer(11)
      notnull: true
    ids_coupon:
      type: text
      default: null
    money:
      type: float
      notnull: true
      default: 0
    status:
      type: integer(1)
      notnull: true
      default: 0
    money_type:
      type: enum
      notnull: true
      values: [qiwi, robokassa, office]
    date_created:
      type: datetime
      notnull: true
  relations:
    profile:
      class: Index_Model_Profile
      local: id_user
      foreign: id
      foreignAlias: checks
      foreignType: many
      owningSide: true

Index_Model_Page:
  columns:
    id:
      type: integer(11)
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    title:
      type: text
      notnull: true
    text:
      type: text
      notnull: true
Index_Model_CouponSms:
  columns:
    id:
      type: integer(11)
      primary: true
      notnull: true
      autoincrement: true
    cuopon_id:
      type: integer(11)
      notnull: true
    date:
      type: datetime
  relations:
    coupon:
      class: Index_Model_Coupon
      local: cuopon_id
      foreign: id
      foreignAlias: sms
      foreignType: many
      owningSide: true
  indexes:
    fk_couponSms_1:
      fields: [cuopon_id]

