<?=$this->layout()->header?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php $this->headTitle()->setSeparator(' / '); ?>
<?=$this->headTitle('HandMade'); ?>

 <?// stylesheets
            $this->headLink()
                ->appendStylesheet('/css/main.css')
                ->appendStylesheet('/css/my_style.css');
                // ->appendStylesheet('/css/common.css')
                // ->appendStylesheet('/css/ajax_styles.css')
                // ->appendStylesheet('/css/style.css'); ?>
        <?=$this->headLink(); ?>
        
        <?// javascript files
            $this->headScript()
                ->prependFile('/js/jquery.js')
                ->appendFile('/js/menu.js');
                // ->appendFile('/js/forms.js'); ?>
        <?=$this->headScript(); ?>
<title></title>
</head>
<body>
<table width="100%" border="0">
	<tr>
		<td width="10%">
 		</td>
		<td width="80%">
			<?//= $this->layout()->content ?>
			<?= $this->action('menu', 'module','product');?>    
			<?//= $this->action('editorschoice', 'module','product');?>    
		</td>
		<td width="10%">
 		</td>
	</tr>
</table>
</body>
