<?php

/**
 * Banner_Model_Base_Main
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $main_id
 * @property clob $text
 * @property integer $template_id
 * @property integer $user_id
 * @property integer $status_id
 * @property integer $product_id
 * @property timestamp $date_start
 * @property timestamp $date_end
 * @property integer $period
 * @property Banner_Model_Template $Template
 * @property User_Model_User $User
 * @property Banner_Model_Status $Status
 * @property Product_Model_Product $Product
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Banner_Model_Base_Main extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('Banner__Model__Main');
        $this->hasColumn('main_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('text', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));
        $this->hasColumn('template_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('status_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('date_start', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('date_end', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('period', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));


        $this->index('M_Template', array(
             'fields' => 
             array(
              0 => 'template_id',
             ),
             ));
        $this->index('M_User', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->index('M_Status', array(
             'fields' => 
             array(
              0 => 'status_id',
             ),
             ));
        $this->index('M_Product', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Banner_Model_Template as Template', array(
             'local' => 'template_id',
             'foreign' => 'template_id'));

        $this->hasOne('User_Model_User as User', array(
             'local' => 'user_id',
             'foreign' => 'user_id'));

        $this->hasOne('Banner_Model_Status as Status', array(
             'local' => 'status_id',
             'foreign' => 'status_id'));

        $this->hasOne('Product_Model_Product as Product', array(
             'local' => 'product_id',
             'foreign' => 'product_id'));
    }
}