<?php

/**
 * Banner_Model_Base_Statu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $status_id
 * @property string $title
 * @property Doctrine_Collection $Banner__Model__Mains
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Banner_Model_Base_Statu extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('Banner__Model__Status');
        $this->hasColumn('status_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Banner_Model_Main as Banner__Model__Mains', array(
             'local' => 'status_id',
             'foreign' => 'status_id'));
    }
}