<?php

/**
 * Banner_Model_Base_Template
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $template_id
 * @property clob $template
 * @property clob $description
 * @property Doctrine_Collection $Banner__Model__Mains
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Banner_Model_Base_Template extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('Banner__Model__Templates');
        $this->hasColumn('template_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('template', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));
        $this->hasColumn('description', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Banner_Model_Main as Banner__Model__Mains', array(
             'local' => 'template_id',
             'foreign' => 'template_id'));
    }
}