<?php

/**
 * Index_Model_CheckTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Index_Model_CheckTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Index_Model_CheckTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Index_Model_Check');
    }
}