<?php

/**
 * Index_Model_CouponTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Index_Model_CouponTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Index_Model_CouponTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Index_Model_Coupon');
    }
}