<?php

/**
 * Index_Model_ProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Index_Model_ProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Index_Model_ProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Index_Model_Profile');
    }
}