<?php

/**
 * Cart_Model_CartTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Cart_Model_CartTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Cart_Model_CartTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cart_Model_Cart');
    }
}