<?php

/**
 * Product_Model_Color
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Product_Model_Color extends Product_Model_Base_Color
{
    public static function getMultiOptions()
    {
        return Doctrine_Query::create()
               ->from('Product_Model_Color')
               ->orderBy('color_id asc')
               ->execute()
               ->toKeyValueArray('color_id', 'title');
    }
}