<?php

/**
 * Product_Model_EventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Product_Model_EventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Product_Model_EventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product_Model_Event');
    }
}