<?php

/**
 * Product_Model_MaterialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Product_Model_MaterialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Product_Model_MaterialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product_Model_Material');
    }
	public function getCompareMaterials($term) {
		return $this->createQuery()
					->where("title LIKE '%$term%'")
					->limit(10)
					->fetchArray();
	}
}