<?php

/**
 * Product_Model_MaterialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Product_Model_MaterialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Product_Model_MaterialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product_Model_Material');
    }
    
    /**
     * Get Compare Material by like $term
     * @param string $term
     * @return type 
     */
    public function getCompareMaterials($term) {
            return $this->createQuery()
                                    ->where("title LIKE '%$term%'")
                                    ->limit(10)
                                    ->fetchArray();
    }
    
    /**
     * Get materials by $productId
     * @param int $productId
     * @return array 
     */
    public function getMaterialsByProductId($productId)
    {
        return $this->createQuery('tag')
            ->where('tag.material_id IN (SELECT materialProduct.material_id FROM Product_Model_MaterialProduct materialProduct WHERE materialProduct.product_id = ?)', $productId)
            ->fetchArray();
    }
}