<?php

/**
 * Product_Model_ProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Product_Model_ProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Product_Model_ProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product_Model_Product');
    }
	public function getProducts($product_ids) {
		return $this->createQuery()
					->whereIn('product_id',$product_ids)
					->andWhere('published = ? ', 1)
					->execute()
					->toArray();
	}
}