<?php

/**
 * Product_Model_SizeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Product_Model_SizeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Product_Model_SizeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product_Model_Size');
    }
}