<?php

/**
 * Index_Model_Base_Check
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_user
 * @property text $ids_coupon
 * @property float $money
 * @property integer $status
 * @property enum $money_type
 * @property datetime $date_created
 * @property Index_Model_Profile $profile
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Index_Model_Base_Check extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('index__model__check');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('id_user', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('ids_coupon', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('money', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => '1',
             ));
        $this->hasColumn('money_type', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 'qiwi',
              1 => 'robokassa',
              2 => 'office',
             ),
             ));
        $this->hasColumn('date_created', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Index_Model_Profile as profile', array(
             'local' => 'id_user',
             'foreign' => 'id',
             'owningSide' => true));
    }
}