<?php

/**
 * Index_Model_Base_Comment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $deal_id
 * @property integer $user_id
 * @property text $text
 * @property datetime $date
 * @property Index_Model_Profile $profile
 * @property Index_Model_Deal $deal
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Index_Model_Base_Comment extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('index__model__comment');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('deal_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('user_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('text', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('date', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));


        $this->index('fk_comment_1', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->index('fk_comment_2', array(
             'fields' => 
             array(
              0 => 'deal_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Index_Model_Profile as profile', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'owningSide' => true));

        $this->hasOne('Index_Model_Deal as deal', array(
             'local' => 'deal_id',
             'foreign' => 'id',
             'owningSide' => true));
    }
}