<?php

/**
 * Index_Model_Base_Coupon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $deal_id
 * @property integer $user_id
 * @property string $code
 * @property boolean $paid
 * @property datetime $date_paid
 * @property Index_Model_Deal $deal
 * @property Index_Model_Profile $profile
 * @property Doctrine_Collection $sms
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Index_Model_Base_Coupon extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('index__model__coupon');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('deal_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('user_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('code', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('paid', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('date_paid', 'datetime', null, array(
             'type' => 'datetime',
             ));


        $this->index('fk_coupon_1', array(
             'fields' => 
             array(
              0 => 'deal_id',
             ),
             ));
        $this->index('fk_coupon_2', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Index_Model_Deal as deal', array(
             'local' => 'deal_id',
             'foreign' => 'id',
             'owningSide' => true));

        $this->hasOne('Index_Model_Profile as profile', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'owningSide' => true));

        $this->hasMany('Index_Model_CouponSms as sms', array(
             'local' => 'id',
             'foreign' => 'cuopon_id'));
    }
}