<?php

/**
 * Index_Model_Base_CouponSms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $cuopon_id
 * @property datetime $date
 * @property Index_Model_Coupon $coupon
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Index_Model_Base_CouponSms extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('index__model__coupon_sms');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('cuopon_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('date', 'datetime', null, array(
             'type' => 'datetime',
             ));


        $this->index('fk_couponSms_1', array(
             'fields' => 
             array(
              0 => 'cuopon_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Index_Model_Coupon as coupon', array(
             'local' => 'cuopon_id',
             'foreign' => 'id',
             'owningSide' => true));
    }
}