<?php

/**
 * Index_Model_Base_Deal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $category_id
 * @property integer $firm_id
 * @property string $name
 * @property text $title
 * @property text $description
 * @property integer $price
 * @property integer $discount
 * @property integer $min_buy
 * @property integer $max_buy
 * @property integer $total_price
 * @property text $extra
 * @property text $conditions
 * @property integer $rating
 * @property datetime $date_start
 * @property datetime $date_end
 * @property integer $coupon_paid
 * @property integer $coupon_ordered
 * @property string $image_url
 * @property string $image_alt
 * @property datetime $use_start
 * @property datetime $use_end
 * @property Index_Model_Category $category
 * @property Doctrine_Collection $comments
 * @property Doctrine_Collection $images
 * @property Doctrine_Collection $coupons
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Index_Model_Base_Deal extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('index__model__deal');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('category_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('firm_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('title', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('price', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('discount', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('min_buy', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => '11',
             ));
        $this->hasColumn('max_buy', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => '11',
             ));
        $this->hasColumn('total_price', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('extra', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('conditions', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('rating', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 100,
             'length' => '11',
             ));
        $this->hasColumn('date_start', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
        $this->hasColumn('date_end', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
        $this->hasColumn('coupon_paid', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('coupon_ordered', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('image_url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('image_alt', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '255',
             ));
        $this->hasColumn('use_start', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => false,
             ));
        $this->hasColumn('use_end', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => false,
             ));


        $this->index('fk_deal_1', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Index_Model_Category as category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'owningSide' => true));

        $this->hasMany('Index_Model_Comment as comments', array(
             'local' => 'id',
             'foreign' => 'deal_id'));

        $this->hasMany('Index_Model_Image as images', array(
             'local' => 'id',
             'foreign' => 'deal_id'));

        $this->hasMany('Index_Model_Coupon as coupons', array(
             'local' => 'id',
             'foreign' => 'deal_id'));
    }
}