<?php

/**
 * Index_Model_Base_Profile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property float $money
 * @property boolean $active
 * @property Doctrine_Collection $comments
 * @property Doctrine_Collection $coupons
 * @property Doctrine_Collection $transactions
 * @property Doctrine_Collection $checks
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Index_Model_Base_Profile extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('index__model__profile');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('money', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Index_Model_Comment as comments', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Index_Model_Coupon as coupons', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Index_Model_Transaction as transactions', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Index_Model_Check as checks', array(
             'local' => 'id',
             'foreign' => 'id_user'));
    }
}