<?php

/**
 * User_Model_Base_Comment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $comment_id
 * @property clob $text
 * @property timestamp $date
 * @property integer $product_id
 * @property integer $user_id
 * @property clob $answer
 * @property integer $emotion_id
 * @property integer $number_comment
 * @property User_Model_Emotion $emotion
 * @property Product_Model_Product $product
 * @property User_Model_User $user
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class User_Model_Base_Comment extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('User__Model__Comments');
        $this->hasColumn('comment_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('text', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('answer', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));
        $this->hasColumn('emotion_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('number_comment', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));


        $this->index('C_Emotion', array(
             'fields' => 
             array(
              0 => 'emotion_id',
             ),
             ));
        $this->index('C_Product', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
        $this->index('C_User', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User_Model_Emotion as emotion', array(
             'local' => 'emotion_id',
             'foreign' => 'emotion_id'));

        $this->hasOne('Product_Model_Product as product', array(
             'local' => 'product_id',
             'foreign' => 'product_id'));

        $this->hasOne('User_Model_User as user', array(
             'local' => 'user_id',
             'foreign' => 'user_id'));
    }
}