<?php

/**
 * User_Model_Base_Country
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $country_id
 * @property string $title
 * @property Doctrine_Collection $User__Model__Regions
 * @property Doctrine_Collection $User__Model__ShippAddresses
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class User_Model_Base_Country extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('User__Model__Countries');
        $this->hasColumn('country_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User_Model_Region as User__Model__Regions', array(
             'local' => 'country_id',
             'foreign' => 'country_id'));

        $this->hasMany('User_Model_ShippAddress as User__Model__ShippAddresses', array(
             'local' => 'country_id',
             'foreign' => 'country_id'));
    }
}