<?php

/**
 * User_Model_Base_Delivery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $delivery_id
 * @property string $title
 * @property clob $description
 * @property Doctrine_Collection $User__Model__DeliveryShops
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class User_Model_Base_Delivery extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('User__Model__Delivery');
        $this->hasColumn('delivery_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User_Model_DeliveryShop as User__Model__DeliveryShops', array(
             'local' => 'delivery_id',
             'foreign' => 'delivery_id'));
    }
}