<?php

/**
 * User_Model_Base_Emotion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $emotion_id
 * @property string $title
 * @property Doctrine_Collection $User__Model__Comments
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class User_Model_Base_Emotion extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('User__Model__Emotions');
        $this->hasColumn('emotion_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User_Model_Comment as User__Model__Comments', array(
             'local' => 'emotion_id',
             'foreign' => 'emotion_id'));
    }
}