<?php

/**
 * User_Model_Base_Message
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $message_id
 * @property clob $text
 * @property timestamp $date
 * @property integer $user_id
 * @property integer $whom_user_id
 * @property boolean $status
 * @property boolean $replied
 * @property boolean $deleted
 * @property User_Model_User $user
 * @property User_Model_User $whomUser
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class User_Model_Base_Message extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('User__Model__Messages');
        $this->hasColumn('message_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('text', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('whom_user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('replied', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('deleted', 'boolean', null, array(
             'type' => 'boolean',
             ));


        $this->index('M_User', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->index('M_Whom_User', array(
             'fields' => 
             array(
              0 => 'whom_user_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User_Model_User as user', array(
             'local' => 'user_id',
             'foreign' => 'user_id'));

        $this->hasOne('User_Model_User as whomUser', array(
             'local' => 'whom_user_id',
             'foreign' => 'user_id'));
    }
}