<?php

/**
 * User_Model_Base_PaymentsShop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $paymentShop_id
 * @property integer $shop_id
 * @property integer $payment_id
 * @property User_Model_Shop $shop
 * @property User_Model_Payment $payment
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class User_Model_Base_PaymentsShop extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('User__Model__PaymentsShops');
        $this->hasColumn('paymentShop_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('shop_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('payment_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));


        $this->index('shopPayment', array(
             'fields' => 
             array(
              'shop_id' => 
              array(
              'sorting' => 'ASC',
              ),
              'payment_id' => 
              array(
              'sorting' => 'ASC',
              ),
             ),
             'type' => 'unique',
             ));
        $this->index('PS_Shop', array(
             'fields' => 
             array(
              0 => 'shop_id',
             ),
             ));
        $this->index('PS_Payment', array(
             'fields' => 
             array(
              0 => 'payment_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User_Model_Shop as shop', array(
             'local' => 'shop_id',
             'foreign' => 'shop_id'));

        $this->hasOne('User_Model_Payment as payment', array(
             'local' => 'payment_id',
             'foreign' => 'payment_id'));
    }
}