<?php

/**
 * User_Model_Base_Region
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $region_id
 * @property string $title
 * @property integer $country_id
 * @property User_Model_Country $country
 * @property Doctrine_Collection $User__Model__Cities
 * @property Doctrine_Collection $User__Model__ShippAddresses
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class User_Model_Base_Region extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('User__Model__Regions');
        $this->hasColumn('region_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('country_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));


        $this->index('R_Country', array(
             'fields' => 
             array(
              0 => 'country_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User_Model_Country as country', array(
             'local' => 'country_id',
             'foreign' => 'country_id'));

        $this->hasMany('User_Model_City as User__Model__Cities', array(
             'local' => 'region_id',
             'foreign' => 'region_id'));

        $this->hasMany('User_Model_ShippAddress as User__Model__ShippAddresses', array(
             'local' => 'region_id',
             'foreign' => 'region_id'));
    }
}