<?php

/**
 * User_Model_Base_Shop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $shop_id
 * @property integer $user_id
 * @property string $title
 * @property string $domain
 * @property clob $additional_payment_condition
 * @property clob $additional_delivery_condition
 * @property clob $about
 * @property clob $return
 * @property User_Model_User $User
 * @property Doctrine_Collection $DeliveryShop
 * @property Doctrine_Collection $PaymentShop
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class User_Model_Base_Shop extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('User__Model__Shops');
        $this->hasColumn('shop_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('domain', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('additional_payment_condition', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));
        $this->hasColumn('additional_delivery_condition', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));
        $this->hasColumn('about', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));
        $this->hasColumn('return', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));


        $this->index('S_User', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User_Model_User as User', array(
             'local' => 'user_id',
             'foreign' => 'user_id'));

        $this->hasMany('User_Model_DeliveryShop as DeliveryShop', array(
             'local' => 'shop_id',
             'foreign' => 'shop_id'));

        $this->hasMany('User_Model_PaymentsShop as PaymentShop', array(
             'local' => 'shop_id',
             'foreign' => 'shop_id'));
    }
}