<?php

/**
 * User_Model_PaymentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User_Model_PaymentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object User_Model_PaymentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User_Model_Payment');
    }
	public function fetchAll() {
		$rows = $this->findAll()->toArray();
		$payments = array();
		foreach($rows as $row) {
			$payments[$row['payment_id']] = $row['title'];
		}
		return $payments;
	}
}