<?php

/**
 * User_Model_PaymentsShopTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User_Model_PaymentsShopTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object User_Model_PaymentsShopTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User_Model_PaymentsShop');
    }
}