<?php

/**
 * Product_Model_Base_ColorProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $colorProduct_id
 * @property integer $product_id
 * @property integer $color_id
 * @property Product_Model_Product $product
 * @property Product_Model_Color $color
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Product_Model_Base_ColorProduct extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('Product__Model__ColorProducts');
        $this->hasColumn('colorProduct_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('color_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));


        $this->index('productColor', array(
             'fields' => 
             array(
              'product_id' => 
              array(
              'sorting' => 'ASC',
              ),
              'color_id' => 
              array(
              'sorting' => 'ASC',
              ),
             ),
             'type' => 'unique',
             ));
        $this->index('CP_Product', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
        $this->index('CP_Color', array(
             'fields' => 
             array(
              0 => 'color_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product_Model_Product as product', array(
             'local' => 'product_id',
             'foreign' => 'product_id'));

        $this->hasOne('Product_Model_Color as color', array(
             'local' => 'color_id',
             'foreign' => 'color_id'));
    }
}