<?php

/**
 * Product_Model_Base_Color
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $color_id
 * @property string $title
 * @property Doctrine_Collection $Product__Model__ColorProducts
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Product_Model_Base_Color extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('Product__Model__Colors');
        $this->hasColumn('color_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Product_Model_ColorProduct as Product__Model__ColorProducts', array(
             'local' => 'color_id',
             'foreign' => 'color_id'));
    }
}