<?php

/**
 * Product_Model_Base_Event
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $event_id
 * @property string $title
 * @property string $date_start
 * @property string $date_end
 * @property Doctrine_Collection $Product__Model__EventProducts
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Product_Model_Base_Event extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('Product__Model__Events');
        $this->hasColumn('event_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('date_start', 'string', 6, array(
             'type' => 'string',
             'length' => '6',
             ));
        $this->hasColumn('date_end', 'string', 6, array(
             'type' => 'string',
             'length' => '6',
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Product_Model_EventProduct as Product__Model__EventProducts', array(
             'local' => 'event_id',
             'foreign' => 'event_id'));
    }
}