<?php

/**
 * Product_Model_Base_EventProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $eventProduct_id
 * @property integer $product_id
 * @property integer $event_id
 * @property Product_Model_Product $Product
 * @property Product_Model_Event $Event
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Product_Model_Base_EventProduct extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('Product__Model__EventProducts');
        $this->hasColumn('eventProduct_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('event_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));


        $this->index('EP_Product', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
        $this->index('EP_Event', array(
             'fields' => 
             array(
              0 => 'event_id',
             ),
             ));
        $this->index('productEvent', array(
             'fields' => 
             array(
              'product_id' => 
              array(
              'sorting' => 'ASC',
              ),
              'event_id' => 
              array(
              'sorting' => 'ASC',
              ),
             ),
             'type' => 'unique',
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product_Model_Product as Product', array(
             'local' => 'product_id',
             'foreign' => 'product_id'));

        $this->hasOne('Product_Model_Event as Event', array(
             'local' => 'event_id',
             'foreign' => 'event_id'));
    }
}