<?php

/**
 * Product_Model_Base_SizeProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sizeProduct_id
 * @property integer $product_id
 * @property integer $size_id
 * @property Product_Model_Product $product
 * @property Product_Model_Size $size
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Product_Model_Base_SizeProduct extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('Product__Model__SizeProducts');
        $this->hasColumn('sizeProduct_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('size_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));


        $this->index('SP_Product', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
        $this->index('SP_Size', array(
             'fields' => 
             array(
              0 => 'size_id',
             ),
             ));
        $this->index('productSize', array(
             'fields' => 
             array(
              'product_id' => 
              array(
              'sorting' => 'ASC',
              ),
              'size_id' => 
              array(
              'sorting' => 'ASC',
              ),
             ),
             'type' => 'unique',
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product_Model_Product as product', array(
             'local' => 'product_id',
             'foreign' => 'product_id'));

        $this->hasOne('Product_Model_Size as size', array(
             'local' => 'size_id',
             'foreign' => 'size_id'));
    }
}