<?php

/**
 * Product_Model_Base_Size
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $size_id
 * @property integer $category_id
 * @property string $title
 * @property Product_Model_Category $Category
 * @property Doctrine_Collection $Product__Model__SizeProducts
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Product_Model_Base_Size extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('Product__Model__Size');
        $this->hasColumn('size_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));


        $this->index('S_Category', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product_Model_Category as Category', array(
             'local' => 'category_id',
             'foreign' => 'category_id'));

        $this->hasMany('Product_Model_SizeProduct as Product__Model__SizeProducts', array(
             'local' => 'size_id',
             'foreign' => 'size_id'));
    }
}