<? $this->headScript()->appendFile('/js/editshop.js');?>
<div class="styledform" style="margin-top:20px">
	<h3>Создание магазина</h3>
	<form  action="<?=$this->escape($this->form->getAction());?>" method="<?=$this->escape($this->form->getMethod());?>">
		<table cellpadding="0" cellspacing="0" class="create_shop">
			<tr>
				<td class="label"><?=$this->form->title->getLabel();?></td>
				<td class="data"><?=$this->form->title;?></td>
				<td class="errors">
				<?	if($this->form->title->getMessages()) { ?>
						<ul>
					<?	foreach($this->form->title->getMessages() as $message) {?>
							<li><?=$message;?></li>
					<?	} ?>
						</ul>
				<?	} ?>
				</td>
			</tr>
			<tr>
				<td class="label"><?=$this->form->domain->getLabel();?></td>
				<td class="data"><?=$this->form->domain;?></td>
				<td class="errors">
				<?	if($this->form->domain->getMessages()) { ?>
						<ul>
					<?	foreach($this->form->domain->getMessages() as $message) {?>
							<li><?=$message;?></li>
					<?	} ?>
						</ul>
				<?	} ?>
				</td>
			</tr>			
			<tr>
				<td class="label"><?=$this->form->about->getLabel();?></td>
				<td class="data"><?=$this->form->about;?></td>
				<td class="errors">
				<?	if($this->form->about->getMessages()) { ?>
						<ul>
					<?	foreach($this->form->about->getMessages() as $message) {?>
							<li><?=$message;?></li>
					<?	} ?>
						</ul>
				<?	} ?>
				</td>
			</tr>
			<tr>
				<td class="label"><?=$this->form->payments->getLabel();?></td>
				<td class="data"><?=$this->form->payments;?></td>
				<td class="errors">
				<?	if($this->form->payments->getMessages()) { ?>
						<ul>
					<?	foreach($this->form->payments->getMessages() as $message) {?>
							<li><?=$message;?></li>
					<?	} ?>
						</ul>
				<?	} ?>
				</td>
			</tr>
			<tr>
				<td class="label">&nbsp;</td>
				<td class="data">
					<a href="javascript:void(0)" id="additional_payment_condition" name="additional">
						<?=$this->form->additional_payment_condition->getLabel();?>
					</a>
					<div style="display:none;">
						<?=$this->form->additional_payment_condition;?>
					</div>
				</td>
				<td class="errors">&nbsp;</td>
			</tr>
			<tr>
				<td class="label"><?=$this->form->delivery->getLabel();?></td>
				<td class="data"><?=$this->form->delivery;?></td>
				<td class="errors">
				<?	if($this->form->delivery->getMessages()) { ?>
						<ul>
					<?	foreach($this->form->delivery->getMessages() as $message) {?>
							<li><?=$message;?></li>
					<?	} ?>
						</ul>
				<?	} ?>
				</td>
			</tr>
			<tr>
				<td class="label">&nbsp;</td>
				<td class="data">
					<a href="javascript:void(0)" id="additional_delivery_condition" name="additional">
						<?=$this->form->additional_delivery_condition->getLabel();?>
					</a>
					<div style="display:none;">
						<?=$this->form->additional_delivery_condition;?>
					</div>
				</td>
				<td class="errors">&nbsp;</td>
			</tr>
			<tr>
				<td class="label"><?=$this->form->return->getLabel();?></td>
				<td class="data"><?=$this->form->return;?></td>
				<td class="errors">
				<?	if($this->form->return->getMessages()) { ?>
						<ul>
					<?	foreach($this->form->return->getMessages() as $message) {?>
							<li><?=$message;?></li>
					<?	} ?>
						</ul>
				<?	} ?>
				</td>
			</tr>
			<tr>
				<td class="label">&nbsp;</td>
				<td class="data"><?=$this->form->submit;?></td>
				<td class="errors">
					<?//errors?>
				</td>
			</tr>
		</table>
	</form>
</div>